spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    defer-datasource-initialization: true # data.sql 초기화 필요시 사용
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true

# 환경변수 설정으로 세팅
jwt:
  secret: "ZB67NHMI84Y20zQVFSf8nZfChJoG6rZ+16x8HgzWuw8=" #base64 32byte
  token:
    refresh-expires: 7200000 #2시간
    access-expires: 7200000

# S3
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:
    region:
      static:
    stack:
      auto-: