spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
#        generate_statistics: true
    #defer-datasource-initialization: true 설정 => data.sql 초기화 필요시 사용
        defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      # 시스템 설정이라 바꿔줘야함
  cloud:
    aws:
      s3:
        endpoint: http://localhost:4566 # LocalStack의 기본 S3 엔드포인트
      credentials:
        access-key: test
        secret-key: test
      region:
        static: ap-northeast-2 # LocalStack의 기본 리전 설정

  config:
      activate:
        on-profile: test
# 환경변수 설정으로 세팅
jwt:
  secret: ${JWT_SECRET_KEY} #base64 32byte
  token:
    refresh-expires: 7200000 #2시간
    access-expires: 7200000