spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
#        generate_statistics: true
    defer-datasource-initialization: true # data.sql 초기화 필요시 사용
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      encoding: UTF-8

# 환경변수 설정으로 세팅
jwt:
  secret: ${JWT_SECRET_KEY} #base64 32byte
  token:
    refresh-expires: 7200000 #2시간
    access-expires: 1800000  #30분

# S3
cloud:
  aws:
    credentials:
      access-key: ${S3_SHOUXKREAM_ACCESS_KEY}
      secret-key: ${S3_SHOUXKREAM_SECRET_KEY}
    s3:
      bucket: ${S3_SHOUXKREAM_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false